name: Ping URL
description: "Ping URL until maximum trials have exceeded. If result is not 200 until then, fails the action."

inputs:
  url:
    description: URL to ping
    required: true
  max_trials:
    description: Max no of trials, until actions fails
    required: false
    default: "10"
  delay:
    description: Delay between trials
    required: false
    default: "5"

outputs:
  url-reachable:
   description: Whethere url is reachable or not

runs:
  using: docker
  image: Dockerfile