name: Using Custom Composite Actions
on:
  workflow_dispatch: 
    inputs:
      target-env:
        type: choice
        options:
          - dev
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node and NPM dependancies
        uses: ./.github/actions/composite-cache-deps
        with:
          target-env: ${{ inputs.target-env }}
          node-version: 24.x
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
  