name: Working with Metricies

on:
  workflow_dispatch:
  
jobs:
  test-matricies:
    runs-on: ${{ matrix.os }}
    name: "${{matrix.os}}- ${{matrix.node-version}}- ${{matrix.env}}- ${{matrix.tag}}"
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version: [22.x, 24.x]
        env: [prod, staging]
        exclude:
          - os: windows-latest
            env: staging
        include: 
          - os: macos-latest
            tag: expensive
          - os: ubuntu-latest
            tag: linux
          - os: windows-latest
            node-version: 20.x
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Matrix
        if: ${{ matrix.tag == 'expensive'}}
        run: echo "Test Successeded"