name: Reusable Workflow E2E

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    uses: my-org-38/gh-actions-e2e-tests/.github/workflows/e2e.yaml@main
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}