name: 04- Using Actions

on:
  # push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: # instead of specifying the working directory for each step, we can set it at the job level
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test